version: "2"

services:

  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - testing-lan

  seleniumapp:
    image: serbanghita/selenium-standalone:latest
    ports:
      - "4444:4444"
    networks:
      - testing-lan

networks:
  testing-lan:
    driver: bridge